eadwinCode/django-ninja-extra

ninja_extra/main.py
Please refer to "Protecting docs" section of [https://django-ninja.rest-framework.com/guides/api-docs/](url)
=> Add 'docs_decorator' parameter from NinjaAPI to NinjaExtraAPI

docs/api_controller/index.md
Hi! 
I was trying the sample code in the [Quick Example documentation](https://eadwincode.github.io/django-ninja-extra/api_controller/), and the sample code throws the following error:
```
raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for NinjaResponseSchema
response -> results
field required (type=value_error.missing)
```
Looking further into the documentation, it seems that the `pagination.paginate` decorator no longer works well with `List[UserSchema]`, so I modified it to `pagination.PaginatedResponseSchema[UserSchema]` and the decorator to `pagination.paginate(pagination.PageNumberPaginationExtra, page_size=50)` and it worked.
I have updated the docs accordingly, I hope you find this helpful.
=> Updated pagination part in the Quick Example doc

ninja_extra/controllers/route/route_functions.py
When you add django-orm operations in has_permission, the system will fail with this exception:
`django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.`
For example:
```
def has_permission(
self, request: HttpRequest, controller: "ControllerBase"
) -> bool:
user = request.user
has_perm = True
if hasattr(controller, "model"):
model = controller.model
app = model._meta.app_label
has_perm = user.has_perm(f"{app}.view_{model.__name__}")
if request.method in ("PATCH", "POST"):
has_perm = user.has_perm(f"{app}.change_{model.__name__}")
return bool(user and user.is_authenticated and user.is_active and has_perm)
```
This quick patch will provide a fix.
=> fix: controller_instance.check_permissions can not use django-orm

ninja_extra/controllers/base.py
The typing overloads for the `@api_controller` decorator currently both specify a `Union[Type[ControllerBase], Callable[..., Any], Any]` return type. This is a more general type than what is actually returned, and this results in spurious typing errors. For example,
```python
@api_controller("/path-prefix/")
class MyController(ControllerBase):
...
```
results in the following error in mypy:
```
error: Too many arguments for "ControllerBase"  [call-arg]
```
The `api_controller()` function always returns a `Callable[..., ControllerBase]` when `prefix_or_class` is a string because it needs to return the inner `_decorator()` method in that case so that the controller class can be decorated by the return value. If a `ControllerBase` subclass were to be returned instead, then there would be a …
=> Fix `@api_controller` type signature

.github/workflows/test_full.yml, Makefile, ninja_extra/controllers/base.py, ninja_extra/controllers/model/endpoints.py, ninja_extra/controllers/model/service.py, ninja_extra/controllers/route/route_functions.py, ninja_extra/operation.py, ninja_extra/permissions/base.py, ninja_extra/router.py, ninja_extra/shortcuts.py, pyproject.toml
- Replaced black with ruff
- Bumped up mypy and ruff version
=> Dropped Black 

ninja_extra/controllers/base.py
Hi!
While using controllers, I noticed the typing here is incorrect. It should allow for classes to be passed, not instances!
=> fix(controller): fix typing for controller base

ninja_extra/controllers/base.py
This fixes IDEs complaining about static methods not existing when called on the class.
For example, in Pycharm the `.some_static({"test":"me")` gets marked with a warning:
```python
@api_controller("/")
class SomeController(ControllerBase):
@route.post("some_endpoint")
def some_endpoint(self, params: dict):
return self.some_static(params)  # This is fine
@staticmethod
def some_static(params):
return some_static
SomeController.some_static({"test":"me")  # This is not: "Unresolved attribute reference 'some_static' for class 'ControllerBase'"
```
With the typing fix:
=> Update typing for api_controller decorator

ninja_extra/ordering.py
While I was using ordering, I found out that the response is not what I expected.
```python
@route.get("student")
@ordering(Ordering, ordering_fields=["grade", "age"])
def get_students(self):
return [
{"grade": "A", "age": 21},
{"grade": "B", "age": 22},
{"grade": "C", "age": 23},
#
{"grade": "A", "age": 33},
{"grade": "B", "age": 32},
{"grade": "C", "age": 31},
#
{"grade": "A", "age": 11},
{"grade": "B", "age": 12},
{"grade": "C", "age": 13},
]
```
request it with query `ordering=grade,-age`
expected response:
```json
[
{ "grade": "A", "age": 33 },
{ "grade": "A", "age": 21 },
{ "grade": "A", "age": 11 },
{ "grade": "B", "age": 32 },
{ "grade": "B", "age": 22 },
{ "grade": "B", "age": 12 },
{ "grade": "C", "age": 31 },
{ "grade": "C", "age": 23 },
{ "grade": "C", "age": 13 }
]
```
but …
=> Fix `Ordering` multisort

ninja_extra/controllers/model/builder.py, pyproject.toml
The url_name attribute on _register_action_endpoint, except the create endpoint, points to primary key attribute name ( self._model_pk_name, instance to the model name. Another change: use lower case to url_name.
=> fixing url-names at ModelControllerBuilder

docs/tutorial/throttling.md, ninja_extra/conf/settings.py, ninja_extra/constants.py, ninja_extra/controllers/base.py, ninja_extra/controllers/route/__init__.py, ninja_extra/operation.py, ninja_extra/router.py, ninja_extra/schemas/response.py, ninja_extra/throttling/__init__.py, ninja_extra/throttling/decorator.py, ninja_extra/throttling/model.py, pyproject.toml, tests/test_throthling/test_decorator.py, tests/test_throthling/test_models.py, tests/test_throthling/test_throttle_controller.py, tests/test_throthling/test_throttle_decorator_on_controllers.py, tests/test_throthling/test_throttling_xxf.py
- Adapted throttling model to Ninja Throttling pattern.
- Ninja version bumped up
**N.B**
The current implementation of Ninja Throttle followed a different usage but the classes/functions are still the same. Because of this, there is now a clash between NINJA_EXTRA  and NINJA  throttling settings resulting in having similar throttling classes between both packages that are distinguished by their settings. 
This is temporary and, also a backward compatibility support for projects already using the NINJA_EXTRA throttling pattern in Controller classes.
Projects using the `@throttle` decorator, should switch to the **route definition** `throttle` parameter as described in the [`Ninja throttling doc`](https://django-ninja.dev/guides/throttling/). The `@throttle` will be deprecated soon in …
=> feat: Ninja  V1.2.0 Support

ninja_extra/permissions/base.py, ninja_extra/permissions/common.py, tests/test_permissions.py
BasePermission subclass message can't transmit up to `ninja_extra/controllers/base.py:L181` `check_permissions`
From #193 , I try the double permission with `|` and `&`, but the ninja always return the message is None.
I tried to debug why the message can't be transmitted from my Custom BasePermission subclass and found that the permission object is from `self._get_permissions()`, `ninja_extra.permissions.base.OR object` does not transmit the message attribute from input BasePermissions.
So I write these code and test cases to fix this problem.
```log
---------- coverage: platform linux, python 3.12.3-final-0 -----------
Name                                               Stmts   Miss  Cover   Missing
-------------------------------------------------------------------------------- …
```
=> bugfix: OperandHolder object can't transmit the permission message.

ninja_extra/apps.py
Hello, 
I am currently working with django_injector and I noticed that the ninja_extra module was no longer loaded when it was detected.  I have added the module's configuration to that of django_injector.
Without adding the ninja_extra module, I no longer had access to the request in my controller. 
Let me know if you need more information :)
Or the second solution is to add : 
```
INJECTOR_MODULES = [
"ninja_extra.modules.NinjaExtraModule",
...
]
```
Quentin
=> fix(Injector): When django_injector is install and replace injector instance, add ninja_extra module

ninja_extra/permissions/base.py, ninja_extra/permissions/common.py, ninja_extra/security/session.py, tests/test_permissions.py, tests/test_security/test_session.py
- Fixed resolving authenticated user in request using `auser` method #201
=> fix: Async session auth

ninja_extra/controllers/route/route_functions.py, ninja_extra/operation.py, tests/test_permissions.py, tests/test_route.py, tests/test_throthling/test_models.py
- Change the flow of route validation. Permission check before schema validation.
=> fix: Permission Check Before Schema validation

ninja_extra/__init__.py, ninja_extra/controllers/base.py, tests/test_operation.py
- Maintained controller operation definition order during route computation. That way, routes that are defined first take precedence over others in a Controller class
=> fix: Controller Operation Order

docs/api_controller/api_controller_permission.md, ninja_extra/controllers/base.py, ninja_extra/shortcuts.py, tests/test_controller.py
Added in async methods for `get_object_or_exception` and `get_object_or_none`, which should resolve #215
=> Additional async support for ControllerBase

docs/api_controller/model_controller/01_getting_started.md, docs/api_controller/model_controller/02_model_configuration.md, docs/api_controller/model_controller/03_model_service.md, docs/api_controller/model_controller/04_parameters.md, mkdocs.yml, ninja_extra/controllers/base.py, ninja_extra/controllers/model/schemas.py, ninja_extra/controllers/route/route_functions.py, ninja_extra/pagination/__init__.py, tests/test_api_instance.py, tests/test_model_controller/async_samples.py, tests/test_model_controller/model_service_with_sample.py, tests/test_model_controller/samples.py, tests/test_model_controller/test_model_service_operation.py
- Model Controller documentation revamp
- Added DI support for `ModelService` and `ModelController`
=> feat: ModelService Dependency Injection Support

README.md, docs/api_controller/api_controller_permission.md, docs/index.md, ninja_extra/__init__.py, ninja_extra/controllers/route/context.py, ninja_extra/operation.py, tests/test_controller.py
- Ability to manually trigger route parameter computation. #227 
```python
class IsUserAllowedToUpdate(BasePermission):
def has_permission(self, request: HttpRequest, controller) -> bool:
if not controller.context.has_computed_route_parameters:
controller.context.compute_route_parameters()
data = controller.context.kwargs.get('data')
mydata= data.mydata
```
This is important for cases where permission depends on route parameter data that has not been computed at the point of running the route permissions.
=> fix: RouteContext Refactor

ninja_extra/pagination/models/page_by_number.py, tests/test_model_controller/test_model_controller_schema.py, tests/test_pagination.py
The schema of `PageNumberPaginationExtra` doesn't enforce a minimum value for the page size. It's possible to query a paginated route with `page_size=-1` or with `page_size=0` (which will also cause a 500 because of a `DivisionByZeroError`).
It may be more sound to enforce a minimum value, in order to return a 422 instead of a 404 or a 500 when the users asks for a page size that makes no sense.
=> Min page size

ninja_extra/operation.py
Without this, when register an async controller, the api will break.
=> fix broken async controller register

docs/api_controller/api_controller_async_permission.md, mkdocs.yml, ninja_extra/context.py, ninja_extra/controllers/base.py, ninja_extra/controllers/route/route_functions.py, ninja_extra/permissions/__init__.py, ninja_extra/permissions/base.py, ninja_extra/threading/__init__.py, ninja_extra/threading/sync_worker.py, ninja_extra/types.py, tests/test_async_permissions.py, tests/test_permissions.py
- Added support for Async Permission #248 
- Permission Type can now inject services
- Ability to combine both `async` and `sync` permission types
```python
from ninja_extra import api_controller, http_get
from ninja_extra.permissions import IsAuthenticated, IsAdminUser, AsyncBasePermission
class HasPremiumSubscriptionAsync(AsyncBasePermission):
async def has_permission_async(self, request, controller):
user_profile = await request.user.profile.aget()
return user_profile.has_premium_subscription
@api_controller("/content")
class ContentController:
@http_get("/premium", permissions=[IsAuthenticated() & HasPremiumSubscriptionAsync()])
async def premium_content(self, request):
return {"content": "Premium content"}
@http_get("/special", permissions=[IsAuthenticated() | IsAdminUser()])
async …
```
=> feat: Async Permission and Permission DI Support

ninja_extra/pagination/operations.py
This diff introduces support for both synchronous and asynchronous pagination in the PaginatorOperation class in the ninja_extra/pagination/operations.py file. The key changes include:
1.  Import Updates:
- Added AsyncPaginationBase to the imports from ninja.pagination, alongside the existing PaginationBase.
2.  Paginator Type Update:
- The paginator parameter in the PaginatorOperation class's constructor is updated to accept either PaginationBase or AsyncPaginationBase using Union.
3.  Asynchronous Pagination Logic:
- In the as_view method, the logic for handling pagination is updated to check the type of the paginator.
- If the paginator is of type AsyncPaginationBase, its `apaginate_queryset` method is used.
- Otherwise, the existing synchronous method (paginate_queryset) is wrapped …
=> Using apaginate_queryset when the paginator is AsyncPaginationBase

ninja_extra/logger.py
Django itself uses `django.request`. This allows one to easily silence request-level logs, without silencing all of Django.
=> request_logger: use `django.request` instead of `django`
