eadwinCode/django-ninja-extra

.github/workflows/test_full.yml, ninja_extra/__init__.py, ninja_extra/controllers/base.py, ninja_extra/controllers/route/__init__.py, ninja_extra/controllers/route/route_functions.py, ninja_extra/helper.py, ninja_extra/main.py, ninja_extra/operation.py, ninja_extra/pagination.py, ninja_extra/router.py, ninja_extra/security/__init__.py, ninja_extra/security/api_key.py, ninja_extra/security/http.py, ninja_extra/security/session.py, pyproject.toml, tests/test_async_auth.py, tests/test_controller.py, tests/test_django_ninja_router.py, tests/test_operation.py, tests/test_pagination.py, tests/test_route.py, tests/utils.py
Features:
- Async Route Authentication support
- Async Pagination Support
- Fix #4 issue
=> Async support on Pagination and Route Authentication

ninja_extra/__init__.py, ninja_extra/pagination.py, ninja_extra/schemas/__init__.py, ninja_extra/schemas/response.py, pyproject.toml, tests/test_pagination.py
#7 - fixed default_app_config issue in django >= 4.0
=> Default App config Fix for Django >= 4.0

ninja_extra/controllers/response.py, ninja_extra/controllers/route/__init__.py
fixed type hinting issues in operation responses in py310
=> Python3.10 type hinting fix 

.github/workflows/test_full.yml, mypy.ini, ninja_extra/compatible.py, ninja_extra/operation.py, pyproject.toml
switched to asynccontextmanager for async controller operations
=> asynccontextmanager for async controller operations

ninja_extra/operation.py, tests/test_pagination.py
- Fixed temporary response feature in django-ninja v18.0
=> Ninja18.0 support

ninja_extra/compatible.py, ninja_extra/controllers/base.py, ninja_extra/controllers/route/context.py, ninja_extra/controllers/route/route_functions.py, ninja_extra/details.py, ninja_extra/exceptions.py, ninja_extra/operation.py, ninja_extra/pagination.py, ninja_extra/shortcuts.py, ninja_extra/types.py, tests/test_operation.py
- Merge ControllerOperation to Operation
- Merge AsyncControllerOperation to AsyncOperation
- Merge ControllerPathView to PathView
- Deprecated - `AsyncControllerOperation`, `ControllerOperation`, `ControllerPathView`
- Controller Route operations compartiblity with Functional route operations
=> ControllerOperation And Operation Merge

docs/tutorial/pagination.md, ninja_extra/main.py
- update pagination doc
- moved doc_decorator to kwargs for NinjaExtraAPI for backward compatibility
=> Pagination Doc update

docs/settings.md, docs/tutorial/throttling.md
- Added docs for throttled controller classes
=> Doc update

.coveragerc, .github/workflows/test.yml, .pre-commit-config.yaml, Makefile, ninja_extra/compatible.py, ninja_extra/controllers/registry.py, ninja_extra/controllers/response.py, ninja_extra/controllers/route/route_functions.py, ninja_extra/details.py, ninja_extra/lazy.py, ninja_extra/main.py, ninja_extra/modules.py, ninja_extra/operation.py, ninja_extra/pagination.py, ninja_extra/permissions/base.py, ninja_extra/throttling/model.py, pyproject.toml, tests/conftest.py, tests/test_async_auth.py, tests/test_controller_registry.py, tests/test_controller_response.py, tests/test_dependency_resolver.py, tests/test_django_ninja_router.py, tests/test_exceptions.py, tests/test_generic_patch.py, tests/test_pagination.py, tests/test_permissions.py
=> 100% Test Coverage

ninja_extra/router.py, tests/test_django_ninja_router.py
- Added return type to response schema support to Ninja Router
=>  Ninja Router Return Type as Response Schema

README.md, docs/api_controller/index.md, docs/index.md, docs/route_context.md, docs/service_module_injector.md, docs/tutorial/authentication.md, docs/tutorial/schema.md, docs/tutorial/testing.md, mkdocs.yml
More clear and explanatory documentation on
- dependency injection
- Route Context
- Controller
=> Clear Written Documentation

docs/api_controller/api_controller_permission.md, ninja_extra/__init__.py, ninja_extra/controllers/base.py, ninja_extra/controllers/route/__init__.py, ninja_extra/controllers/route/route_functions.py, ninja_extra/operation.py, ninja_extra/permissions/base.py, ninja_extra/types.py, tests/test_permissions.py
=> Allow permission instance in permissions parameter

docs/tutorial/ordering.md, docs/tutorial/searching.md, ninja_extra/ordering.py, ninja_extra/searching.py, tests/conftest.py, tests/test_ordering.py, tests/test_searching.py
i made mistake in previous version for async. I faced [common GOTCHA](https://django-ninja.rest-framework.com/guides/async-support/) - "Django queryset's are lazily evaluated (database query happens only when you start iterating), so this will not work", there is a fix in this version
=> add list support for filtering

docs/tutorial/authentication.md
Resolved Async Auth Classes Doc [discussion](https://github.com/eadwinCode/django-ninja-extra/discussions/58).
=> Asynchronous Auth Classes Documentation

ninja_extra/schemas/response.py, tests/test_pagination.py
- Fixed Queryset failing when using ninja pagination classes with ninja_extra pagination. #68
=> Ninja pagination response schema fix

docs/tutorial/authentication.md
Changed 'self.request' to 'self.context.request' as announced in #70.
=> Fix authentication.md

Makefile, mypy.ini, ninja_extra/constants.py, ninja_extra/controllers/base.py, ninja_extra/exceptions.py, ninja_extra/modules.py, ninja_extra/operation.py, ninja_extra/signals.py, pyproject.toml, tests/test_async_auth.py, tests/test_operation.py
=> switched to context var

docs/api_controller/index.md, ninja_extra/controllers/base.py, ninja_extra/controllers/response.py, ninja_extra/controllers/route/__init__.py, ninja_extra/controllers/route/route_functions.py, ninja_extra/operation.py, ninja_extra/schemas/__init__.py, ninja_extra/schemas/response.py, tests/test_api_instance.py, tests/test_controller.py, tests/test_controller_response.py, tests/test_generic_patch.py, tests/test_route.py
- Dropped `ControllerResponse`. The idea behind it was just experimental and the code was really messy.
- Increased coverage to 100%
- Cleaned deprecated codes and py3.6 codes
=> Drop controller response

ninja_extra/__init__.py, ninja_extra/testing/client.py
=> TestClient Bug Fix

ninja_extra/controllers/base.py
=> Bug Fixes: Fixed auth=None bug on controller

ninja_extra/operation.py, tests/test_operation.py
=> fix: Operation exception Log Level

ninja_extra/controllers/model/builder.py, ninja_extra/controllers/model/endpoints.py, ninja_extra/controllers/model/schemas.py, ninja_extra/ordering.py, ninja_extra/pagination/operations.py, ninja_extra/searching.py, tests/test_ordering.py, tests/test_pagination.py, tests/test_searching.py
- Multiple response support for decoratorated function #185
=> Fix: Multiple Response

Makefile, requirements-tests.txt
- Upgraded to latest ninja schema package
=> fix: Ninja Schema Upgrade

ninja_extra/__init__.py, ninja_extra/operation.py
- Revert Authentication check before permission checks #212
=> fix: Permission execution time

docs/api_controller/model_controller.md, ninja_extra/controllers/model/schemas.py, requirements-tests.txt, tests/test_model_controller/test_model_controller_configurations.py
- Added support to pass more config options to generated schema in ModelController #174
=> feat: Model config extra options for Model Controller

docs/api_controller/model_controller/02_model_configuration.md, ninja_extra/controllers/model/builder.py
=> Allow customisation of schema_out in route_info dicts

docs/settings.md, ninja_extra/conf/settings.py, ninja_extra/controllers/route/context.py, tests/test_settings.py
=> feat: Added support for custom RouteContext 

ninja_extra/__init__.py, ninja_extra/conf/package_settings.py
- Fixed module lazy import bug from #250
=> fix: Module import error

ninja_extra/__init__.py, pyproject.toml
=> chores: Bumped up Ninja Package
